version: "3.9"
services:
  postgres:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: "testdb"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
#      - ../2. Init Database:/docker-entrypoint-initdb.d
      - vkdb-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  prometheus:
    image: prom/prometheus
    volumes:
      - ./sensors/src/main/resources/:/etc/prometheus/
#      - prometheus_data:/prometheus_iot
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9091:9090
    restart: always
  grafana:
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    ports:
      - 3001:3000
#    volumes:
#      - grafana_data:/var/lib/grafana_iot
    restart: always

volumes:
  vkdb-data: { }
  prometheus_data: { }
#  grafana_data: { }
